- content/zurihac2019/sections/program.html
- css/zurihac.css
> prettify schedule

- content/sections/board.html
Effectuate board changes as per [minutes](https://drive.google.com/file/d/1jGfk20gpzQffWZDJgqdJeXxe7e2LeF-i/view?usp=sharing)
FYI: @achirkin @urv @basvandijk
> Update board composition.

- content/zurihac2019/projects.html
No link yet because Mathieu wants to make it public a bit later.
> Add Ormolu to the projects page

- content/zurihac2019/projects.json
this project is no longer offered at zurihac2019
> remove proposed project

- content/zurihac2019/sections/program.html
> Bump schedule, mostly friday morning

- content/zurihac2019/projects.json
> Add Morley to projects

- content/zurihac2019/projects.json
I think I had proposed this in my application, but it's not in the list, so let's add it :slightly_smiling_face: .
> Add linear types

- content/zurihac2019/projects.json
As per our one project per person rule, we cut down Manu's projects to only list his favourite pick.
> remove two projects

- content/zurihac2019/projects.json
> Add niv to projects

- content/zurihac2019/projects.json
@ndmitchell anyone else I should add as a contact?
> Add haskell ide core to the project list

- content/zurihac2019/projects.json
We have created a web page about Morley for ZuriHac, so the link here should be updated accordingly.
> Update link to Morley

- content/zurihac2019/projects.json
Too many other interesting projects! :-)
> Remove beans

- content/zurihac2019/projects.json
See https://github.com/purescript/purescript/issues/3613 for details.
> Add PureScript ES Modules project proposal

- content/zurihac2019/sections/program.html
Simon Hafner offered to give an additional talk at the GHC track.
> Add talk to GHC track

- content/zurihac2019/projects.json
Please add gg to the list of projects. Still in WIP.
> Add gg to the list of projects

- content/zurihac2019/projects.json
Unfortunately, I won't be able to attend ZuriHac. Please accept removal of my proposed project.
> Remove GHC dynamic linking project

- content/zurihac2020/sections/venue.html
initial wording, let me know what you think
> monadic party info

- content/sections/about-us.html
Make the sign up button to refer to the new form that does not provide the paid membership option.
> Update membership section

- content/zurihac2020/projects.json
Added project, on which I will work on.
> Added project.

- content/zurihac2020/projects.json
My project name has been changed from `implicit-effects` to `casimir`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zfoh/zfoh.ch/100)
> Update project name

- content/zurihac2020/projects.json
Adding my project which can be found [here](https://github.com/therewillbecode/poker-maison).
> Update projects.json with poker project

- content/zurihac2020/projects.json
This is something I'm planning to work on (and can help others if they want to join).
> Add Xmobar

- content/zurihac2020/projects.json
Adds the project that I intent to work on (Chromar).
> Adds a project

- content/zurihac2020/projects.json
> Add HaskellKatas link

- content/zurihac2021/projects.json
Learn IHP, grow a repo with sample solutions
> Add ihp-guide

- content/zurihac2021/projects.json
We are labeling some of our feature requests as ZuriHac friendly: they are small to medium features with direct impact in the user experience!
https://github.com/haskell/haskell-language-server/issues?q=is%3Aissue+is%3Aopen+label%3A%22ZuriHac+2021%22
> Add haskell-language-server

- content/zurihac2021/projects.json
> Fix name of haskell-syntaxonomer

- content/zurihac2021/projects.json
Broke it in my previous pull request
> Fix broken Json string

- content/zurihac2022/projects.json
I have actually implemented my original proposal so I can now propose a tutorial / workshop explaining how to use the library for:
- building medium to large applications (something that can be puzzling for beginners)
- wiring data generators for tests
- implementing flexible encoders / decoders for evolving data graphs
> Updated the registry proposal

- content/zurihac2022/projects.json
> Add Space to project list.

- content/zurihac2023/projects/projects.json
We have a couple people from di at ZuriHac hacking on IHP 👍
> Added IHP to projects

- content/zurihac2023/projects/projects.json
> Add Clash Compiler to `projects.json`

- content/zurihac2023/projects/projects.json
> Typo in @dylan-thinnes’s project URL

- content/sections/board.html
> Add new Board

- content/zurihac2024/projects/projects.json
> Update projects.json. Add Mensam.

- .gitignore
- README.md
- flake.lock
- flake.nix
In the true spirit of Nix, we don't have to change anything about the project itself. :slightly_smiling_face:
> add Nix Flake

- content/zurihac2024/index.html
Thanks a lot for adding me to the website :) here is my Haskell-related mastodon handle, maybe that is of interest for some fediverse folks.
> zurihac 2024: Add mastodon handle for Manuel Bärenz

- content/zurihac2024/projects/projects.json
> Add "cabal hacking" project

- content/zurihac2024/projects/projects.json
> Add Copilot project.

- content/zurihac2024/projects/projects.json
> projects: add wxHaskell

- content/zurihac2025/index.html
> add bluesky to social media links

- content/zurihac2025/projects/projects.json
Added a link to the GitHub page for data frame library.
> Add Dataframe project link

- content/zurihac2025/projects/projects.json
> Add Copilot to projects
